//
//  Constants.swift
//  MutipurposeApp
//
//  Created by Sandeep on 27/09/24.
//

class Constant {
    static let privacyPolicyUrl = ""
    static let appStoreUrl = "https://apps.apple.com/"
    static let GUID = "00000000-0000-0000-0000-000000000000"
    //MARK: Message
    static let SOMETHING_WRONG = "Something Went Wrong"
    static let UNAUTHORIZED = "Unauthorized"
    static let INTERNAL_SERVER_ERROR = "Internal Server Error"
    static let REQUEST_TIMEOUT = "The request timed out."
    static let SPECIFY_LOCATION = "Please specify your location"
    static let NO_INTERNET = "No Network Available. Retry later"
    static let CONNECTED_INTERNET = "Network Available"
    static let FAILED_PARSE = "Failed to parse data"
    //Travel
    static let magnifyingglass = "magnifyingglass"
    static let whereDoYouWantToGo = "Where do you want to go?"
    static let discover = "Discover"
    static let defaults  = "Default"
    static let art = "Art"
    static let sport = "Sport"
    static let liveEvents = "Live Events"
    static let food = "Food"
    static let history = "History"
    static let paintPaletteFill = "paintpalette.fill"
    static let sportsCourtFill = "sportscourt.fill"
    static let musicMic = "music.mic"
    static let rectangleAndPencilAndEllipsis = "rectangle.and.pencil.and.ellipsis"
    static let forkKnife = "fork.knife"
    static let loading = "Loading..."
    static let xmarkOctagonFill = "xmark.octagon.fill"
    static let paris = "Paris"
    static let france = "France"
    static let eiffel_tower = "eiffel_tower"
    static let tokiyo = "Tokiyo"
    static let japan = "japan"
    static let newYork = "New york"
    static let us = "US"
    static let new_york = "new_york"
    static let jaunpur = "Jaunpur"
    static let uttarPradesh = "Uttar Pradesh"
    static let popularDestinations = "Popular destinations"
    static let seeAll = "See all"
    static let tileModifier = "TileModifier"
    static let eiffelTower = "Eiffel Tower"
    static let champsElysees = "Champs-Elysees"
    static let louvreMuseum = "Louvre Museum"
    static let art2 = "art2"
    static let starFill = "star.fill"
    static let location = "Location"
    static let hide = "Hide"
    static let show = "Show"
    static let attraction = "Attraction"
    static let restaurantDetail = "Restaurant Detail"
    static let seeMorePhotos = "See more photos"
    static let locationDescription = "Location & Description"
    static let contact = "Contact"
    static let follow = "Follow"
    
}
